[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
obridge = "2pN84sZ1F5ByDJBMgN31UX2e8tEusaiDF1GD7kj2b9Hs"

[programs.devnet]
obridge = "2pN84sZ1F5ByDJBMgN31UX2e8tEusaiDF1GD7kj2b9Hs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
